### ISSUE TITLE
Push docker versions

### ISSUE THREAD

**Issue by omid** [omid/gitversion#5]
- Read the docker version from Cargo.toml, and push _the version_ + _latest_

**Comment by Deepeshac2890** [comment]
Can you please explain it in a little bit detail what we have to do in this issue.

**Comment by omid** [comment]
Currently, we only push the "latest" version to docker hub.
This issue is about to extend Makefile's _build_docker_ and _push_docker_ commands, to read the version from the Cargo.toml, and build and push the Cargo.toml version plus the _latest_ tag.

**Comment by tjtelan** [comment]
I just opened a PR. I hope this is what you were looking for. I tried to use only standard shell utilities that would be on typical Linux/MacOS environments. I make the assumption that the version number is always in the top 4 lines of the `Cargo.toml` file.

**Comment by omid** [comment]
Thanks.

Anyhow, docker does exist in that system, so you can use docker if you think `cargo` is not available.
